system:
  domain: fire
  version: 1.0
  env: "dev"
  HttpPort: ":5000"
  #Host: "127.0.0.1"
  Host: "192.168.31.232"
  UploadModel: "local"
  StartTime: "2024-10-20"
  MachineID: 1


mysql:
    dialect: "mysql"
    dbHost: "127.0.0.1"
    dbPort: "3306"
    dbName: "fire_tmp"
    userName: "root"
    password: "abc123"
    charset: "utf8mb4"

redis:
  redisDbName: 4
  redisHost: 127.0.0.1
  redisPort: 6379
  redisPassword: abc123
  redisNetwork: "tcp"

email:
  ValidEmail: http://127.0.0.1:5000/
  SmtpHost: "smtp.qq.com"
  SmtpEmail: "2098128799@qq.com"
  SmtpPass: "eufkdzjfgigvbahd"

encryptSecret:
  jwtSecret: "FanOne666Secret"
  emailSecret: "EmailSecret"
  phoneSecret: "PhoneSecret"

path:
  photoHost: "http://8.136.113.100"
  avatarPath: "/static/imgs/avatar/"